In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data=data)

In [3]:
np_arr = np.array(data)
torch.from_numpy(np_arr)

tensor([[1, 2],
        [3, 4]])

In [4]:
torch.arange(0,11,2).reshape(2,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10]])

In [5]:
torch.zeros_like(x_data)

tensor([[0, 0],
        [0, 0]])

In [6]:
np.zeros_like(x_data)

array([[0, 0],
       [0, 0]])

In [7]:
torch.rand((2,3,))

tensor([[0.4711, 0.4448, 0.8180],
        [0.5687, 0.7736, 0.4235]])

In [16]:
torch.normal(0,1,(2,3))

tensor([[ 0.0045,  1.1637, -0.2739],
        [-0.0360, -1.0430,  1.4538]])

In [20]:
torch.full((3,2), 7)

tensor([[7, 7],
        [7, 7],
        [7, 7]])

In [10]:
torch.ones(2,3, dtype=torch.long)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [11]:
torch.ones(2,3, dtype=torch.long) @ torch.full((3,2), 7)

tensor([[21, 21],
        [21, 21]])