In [10]:
## Let get start to numpy
# Import Numpy
import numpy as np

In [11]:
## Checking numpy's version
np.__version__

'1.23.1'

In [3]:
## Great, we are on the latest version of numpy.
## Let's take a look at numpy's data structure, array.


In [4]:
## A numpy's array is a multidimensional table of numbers
# Which can be expressed in Python using Lists.
# Example:
[
    [1, 2, 3],
    [4, 5, 6]
] 
## 2-D array: we can also view this as a matrix. (1,2,3) is  a row whereas (1,4) is a column
## This is a 3x2 matrix. 

[[1, 2, 3], [4, 5, 6]]

In [6]:
## So that numpy keeps this in mind and create a new data structure call array.
## Note: This is difference from array.array (the built-in array in Python.)
import array
a = array.array("i", [1,2,3,4])
print(a)

array('i', [1, 2, 3, 4])


In [7]:
dir(a)

['__add__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'buffer_info',
 'byteswap',
 'count',
 'extend',
 'frombytes',
 'fromfile',
 'fromlist',
 'fromunicode',
 'index',
 'insert',
 'itemsize',
 'pop',
 'remove',
 'reverse',
 'tobytes',
 'tofile',
 'tolist',
 'tounicode',
 'typecode']

In [8]:
a.append(6)
print(a)

array('i', [1, 2, 3, 4, 6])


In [9]:
## Array module does not have many functionalities for computational.
## Numpy array is different. It is for scientific Computation. 
## Numpy is faster than pure Python!

In [12]:
## The basic object in Numpy is `ndarray`
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [13]:
np.array([
    [1, 2, 3],
    [4, 5, 6]
] )

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
] )

In [17]:
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [18]:
## (# rows, # columns)
## But if 1D, column is not exist!
np.array([1,2,3,4]).shape

(4,)

In [23]:
print(arr.dtype)
np.array([1,2,3,4], dtype=np.int8)

int64


array([1, 2, 3, 4], dtype=int8)

In [24]:
np.dtype

numpy.dtype

In [26]:
arr.size == arr.shape[0] * arr.shape[1]

True

In [27]:
# 1 mistake that beginners sometimes make
np.array(1, 2, 3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [29]:
# ways to create numpy array other than np.array
np.zeros(shape=(5,5)) # 5x5 zero matrix


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
np.eye(5, dtype=np.int64) # 5x5 identity matrix


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [33]:
np.diag([1,1,1,1,1])

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [35]:
np.full((2,3), 6)

array([[6, 6, 6],
       [6, 6, 6]])

In [36]:
np.ones((2,3)) * 6

array([[6., 6., 6.],
       [6., 6., 6.]])

In [37]:
np.zeros((2,3)) + 6 # This is broadcasting


array([[6., 6., 6.],
       [6., 6., 6.]])

In [38]:
## You can create a ndarray using 
np.arange(5)

array([0, 1, 2, 3, 4])

In [39]:
np.array(range(5))

array([0, 1, 2, 3, 4])

In [40]:
np.arange(10, 100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
# np.linspace: given the start, end (inclusive), and the number of elements
# Example
np.linspace(0,1,11)
## 11 elements between [0,1]

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [42]:
np.random


<module 'numpy.random' from '/usr/lib/python3.10/site-packages/numpy/random/__init__.py'>

In [47]:
import random 
random.seed(34)
random.randint(0,10)

8

In [50]:
np.random.seed(34)
np.random.randint(0, 10, size=(3,4))

array([[1, 9, 6, 5],
       [4, 3, 5, 2],
       [9, 8, 6, 5]])

In [52]:
l = []
for i in range(12):
    l.append(random.randint(0,10))

np.array(l)
# Cannot create a 3x4 like above

array([5, 9, 0, 3, 0, 6, 5, 1, 6, 4, 5, 1])

In [53]:
# Solution: reshape
np.array(l).reshape((3,4))

array([[5, 9, 0, 3],
       [0, 6, 5, 1],
       [6, 4, 5, 1]])

In [54]:
np.reshape(np.array(l), (3,4))

array([[5, 9, 0, 3],
       [0, 6, 5, 1],
       [6, 4, 5, 1]])

In [55]:
## Numpy array operations broadcast!
a = np.arange(1,7).reshape(2,3)
print(a)

[[1 2 3]
 [4 5 6]]


In [56]:
a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [57]:
a + 6

array([[ 7,  8,  9],
       [10, 11, 12]])

In [62]:
a * (a + 6)
## 7 = 7 * 1
## 16 = 8 * 2 etc
## => A_ij 

array([[ 7, 16, 27],
       [40, 55, 72]])

In [63]:
b = a + 6
print(b.shape)
print(a.shape)

(2, 3)
(2, 3)


In [64]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [65]:
a.T @ b
## 1*7 + 4*10 

array([[47, 52, 57],
       [64, 71, 78],
       [81, 90, 99]])

In [66]:
np.dot(a.T, b)

array([[47, 52, 57],
       [64, 71, 78],
       [81, 90, 99]])

In [68]:
c = np.ones((3,3))
for i in range(3):
    c += i

c 
## c + 1 + 2

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])